export const UserCode = {
  INCORRECT_USERNAME_OR_PASSWORD: 601,
  USERNAME_ALREADY_EXISTS: 602,
  USERNAME_NOT_EXISTS: 603
}
export const CommonCode = {
  SUCCESS: 200,
  FAILED: 500,
  DATA_BINDING_FAILED: 600,
  UNAUTHORIZED: 401,
  ACCESS_DENIED: 403
}
